### PR TITLE
playerDestructionBlock fix

### LINKED ISSUE #46: playerDestructionBlock documentation is misleading
### Issue overview

* [X] Incorrect behavior
* [ ] Feature request
* [ ] Crash
* [X] Help / documentation
* [ ] Other: _classification_

### Description of the problem

Per the documentation, `playerDestructionBlock` is called before the player is nil'd out, as an opportunity to remove observers:

> Three kinds of observers can be set on a player to observe its playback:
> - Usual boundary time and periodic time observers, which you define on the `AVPlayer` instance directly by accessing the `player` property. **You should use the player creation and destruction blocks to install and remove them reliably.**
```objective-c
/**
 *  Optional block which gets called right before player destruction (player changes from not `nil` to `nil`).
 */
@property (nonatomic, copy, nullable) void (^playerDestructionBlock)(void);
```

However, the player destruction block is called *after* the player has been replaced:

```objective-c
- (void)setPlayer:(AVPlayer *)player
{
    BOOL hadPlayer = (_player != nil);
    
    if (_player) {
        // un-register internal observers
    }
    
    _player = player; // player replaced

    if (player) {
        if (! hadPlayer) {
            self.playerCreationBlock ? self.playerCreationBlock(player) : nil;
        }

        // various stuff

    }
    else if (hadPlayer) {
        self.playerDestructionBlock ? self.playerDestructionBlock() : nil; // destruction block called
    }
}
```

Since the `player` isn't passed as an argument in the destruction block, and it's un-set by the time the block is called, a consumer of the library must create his own reference to that player in the creation block and use that reference to remove observers in the destruction block.

```swift
let mediaPlayer = SRGMediaPlayerController()
var timeObserver: Any?
mediaPlayer.playerCreationBlock = { player in
    timeObserver = player.addPeriodicTimeObserver(...)
}
mediaPlayer.playerDestructionBlock = { // no player available
    if let obs = timeObserver {
        mediaPlayer.player?.removePeriodicTimeObserver(obs) // <-- doesn't work, player is nil here
    }
}
```

You have to do this:

```swift
let mediaPlayer = SRGMediaPlayerController()
var timeObserver: Any?
var savedPlayer: AVPlayer?
mediaPlayer.playerCreationBlock = { player in 
    timeObserver = player.addPeriodicTimeObserver(...)
    savedPlayer = player
}
mediaPlayer.playerDestructionBlock = {
    if let obs = timeObserver {
        savedPlayer?.removePeriodicTimeObserver(obs)
    }
    savedPlayer = nil
}
```

### Reproducibility

* [X] Always reproducible
* [ ] Difficult to reproduce

### Suggested Handling

Call the `playerDestructionBlock` just before reassigning that value, and include the old player as an argument in the block.  This will allow someone using SRGMediaPlayer to add & remove observers from the AVPlayer reliably and in a straightforward fashion.

Like so:

```swift
let mediaPlayer = SRGMediaPlayerController()
var timeObserver: Any?
mediaPlayer.playerCreationBlock = { player in 
    timeObserver = player.addPeriodicTimeObserver(...)
}
mediaPlayer.playerDestructionBlock = { player in
    if let obs = timeObserver {
        player.removePeriodicTimeObserver(obs)
    }
}
```

### PR DESCRIPTION
**Pull request by tooolbox**
Fixes #46 

This is more of a suggestion than anything; I didn't touch your tests.

Thanks for the great library!  😄

### CODE REVIEW

**Comment by tooolbox** [comment]
Hm, there's definitely some points I don't understand about the code, as well.  In my app, the creation & destruction blocks are called each time I play a video, but the code looks like it should only call the creation block *if there's no previous player*, and only call the destruction block *if there's no new player*.  Neither of which make sense...

Anyway, just commenting on that because I might have gotten some aspects of this PR wrong, but *for sure* the mediaPlayer's `player` is nil by the time the destruction block is called, so this is my attempt to handle that.

**Comment by pyby** [comment]
Hi @tooolbox ,

Thank you for your sharing code.

- On your [latest commit](https://github.com/SRGSSR/SRGMediaPlayer-iOS/pull/47/commits/b791dd0bf69e187751fe354b56ea33a1142e6002), you moved the `playerDestructionBlock` to be called each time the `setPlayer:` is called.

- When playing a new URL, or stop the current media, the `AVPlayer` is released. So you'll have a new  `playerCreationBlock` call in many cases, like playing a new URL or `stop`and `play` the same URL.

We'll come back to you about [#46](https://github.com/SRGSSR/SRGMediaPlayer-iOS/issues/46).

**Comment by tooolbox** [comment]
- On your first point there, the destruction block *should* be called each time `setPlayer:` is called, right?  A new player is created and assigned every time you start a video playing, so I think the destruction block should be called each time, right?
- Okay, thanks for the clarification.

**Comment by defagos** [comment]
Thanks for your PR. The documentation was clearly incorrect.

Your PR correctly fixes the code so that it matches the documentation. I pushed an additional commit to improve the player lifecycle documentation, which was not clear enough about the fact that the creation and destruction blocks can be called several times over the course of the controller lifetime, as @pyby said. I also updated the tests to take into account the new block parameter.

What could still be discussed is whether the destruction block must be called right before destruction, or after destruction has occurred. I would say that, for the time being, having the destruction block called before the creation block (in the case of a URL switch, for example) is better, most notably if you perform `AVAudioSession` changes.

We'll discuss the PR with @pyby and merge it accordingly. Thanks for your help!

**Comment by pyby** [comment]
Thank you @tooolbox for the PR. 🎉

**Comment by tooolbox** [comment]
Absolutely guys, glad to help.  Thank *you!*

**Pull request merged**
